const { solve } = require('./src/core/solver.js')
require('./src/app/syntax_highlight_rules.js')
require('./src/app/main.js')
const { getParsedQuery } = require('./src/app/button_controls.js')
const { getParsedProgram } = require("app/main")